### ISSUE TITLE
Add Pinball metric

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting-metrics#31]
## Detailed Description
Would be good to see how well `national_xg` model is doing, and `Pvnet`. Perhaps just do this on National first of all

**Comment by peterdudfield** [comment]
https://www.lokad.com/pinball-loss-function-definition/#:~:text=The%20pinball%20loss%20function%2C%20also,forecast%20is%20a%20subtle%20problem.

**Comment by peterdudfield** [comment]
We could expand this out to Pvnet_2 too now

**Comment by peterdudfield** [comment]
We probably want to do a few probablistic metrics
- pinball
- exceedence, i.e how often the truth value exceeds the p_{XX} value
And would be good to do this in the sql query

**Comment by peterdudfield** [comment]
For getting the values out of the json column. We could use `json_extract_path(properties, '10')`

**Comment by abhijelly** [comment]
@peterdudfield can I take this up if no one is working on this?

**Comment by abhijelly** [comment]
hey @peterdudfield I'm currently giving this a go and in order to test my approach, I believe I need the database - how do I connect to an actual or a dummy database if possible?

**Comment by peterdudfield** [comment]
Hey @abhijelly , ive atcually started this in #41 so this might not be the best one to do. 

Would you like to do https://github.com/openclimatefix/pv-site-production/issues/59 (I will add some more detail to this task)

**Comment by peterdudfield** [comment]
> hey @peterdudfield I'm currently giving this a go and in order to test my approach, I believe I need the database - how do I connect to an actual or a dummy database if possible?

Yea connecting to the main database is going to be hard. In the past we've gone along 
- write code
- added tests, which has a dummy database
- tested it on development database (OCF member)
Sorry I know its not ideal

**Comment by peterdudfield** [comment]
@abhijelly you may want to consider doing this one too - https://github.com/openclimatefix/pv-site-api/issues/124
